POST http://localhost:8080/merge
Authorization: NONE
Content-Type: application/json

{
  "spreadsheetId": "11rCm6yBHLElNXZYZn-F6cZ6lanp3XYnPmQ7GH4zKNkg",
  "sheetId": 1827991267,
  "draftId": "23ws",
  "userEmail": "oleksandr.demian@revevol.eu"
}

###
POST http://localhost:8080/merge
Authorization: NONE
Content-Type: application/json

{
  "spreadsheetId": "11rCm6yBHLElNXZYZn-F6cZ6lanp3XYnPmQ7GH4zKNkg",
  "sheetId": 1827991267,
  "draftId": "r-7011512542691182400",
  "userEmail": "oleksandr@addonsforgapps.com",
  "emailHeader": "Mail"
}

###
