POST http://localhost:8080/merge
Authorization: Bearer ya29.a0AX9GBdWIlqHxgrcUxll5FRgRq6r62_upyi4yv2x5x0dtYkl2P2XHpuxBPyU0iUvdVsbhB5Ub57my4ovt1nfPFS1U4nlUuyF28gs5dVEKGfjbz20qhLFZgVGhMNUp2ksNMJ549MaBQ3hqGho88ukQmhw9hrIQaCgYKARMSARISFQHUCsbCDwNLdxjyjeSGLiu-JfUnSA0163
Content-Type: application/json

{
  "spreadsheetId": "11rCm6yBHLElNXZYZn-F6cZ6lanp3XYnPmQ7GH4zKNkg",
  "sheetId": 1827991267,
  "draftId": "23ws",
  "userEmail": "oleksandr.demian@revevol.eu"
}

###
POST http://localhost:8080/merge
Authorization: Bearer ya29.a0AX9GBdXXRSWhA17_TxOJ98_IU9GydVDkV4BZgitTcvqEz6kouNBQHDkCm7sSWIJ4sXHVMmpX091GLlPHFZycRK-D0NbxKO9RaRfouOJVy7Tr7OfeiHIg9E3eNKLs9OEHtYR5MRHgeRxmiItp46WzMD4JBVlxmFIaCgYKAecSAQASFQHUCsbCYbMV3KqSfcrNdWfW5dpYQQ0166
Content-Type: application/json

{
  "spreadsheetId": "11rCm6yBHLElNXZYZn-F6cZ6lanp3XYnPmQ7GH4zKNkg",
  "sheetId": 1827991267,
  "draftId": "r-7011512542691182400",
  "userEmail": "oleksandr@addonsforgapps.com",
  "emailHeader": "Mail"
}

###
